# Use the official Nginx image to serve static files
FROM nginx:alpine

# Set the working directory
WORKDIR /usr/share/nginx/html

# Copy the static files to the working directory
COPY . .

# Copy our custom nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the default Nginx port
EXPOSE 80

# Nginx runs as default CMD
